window.LIFEINVADER_POLICY={
  "blacklist": [
    "If any of the following terms or items are found in an advertisement, the phone number used in the ad must be blacklisted immediately:",
    "Firearms of any kind",
    "Ammunition",
    "Bulletproof vests",
    "Dark Lui Vi Armored Vest",
    "Weed / cannabis seeds or trees",
    "Drugs and cocaine",
    "EMS surgical masks or medical masks",
    "Vehicle scanners and people scanners (radars)",
    "Balaclava masks",
    "Ropes",
    "Flash drive with a virus (USB)",
    "Lock picks",
    "Troll advertisements",
    "Anti-Radar",
    "Engine Block",
    "Smuggling Machine",
    "Submodule",
    "Hacking the Search Database",
    "It is also strictly forbidden to publish license plates containing offensive or inappropriate language. “Selling license plate (1SEX269). Price: Negotiable.”"
  ],
  "rejectOnly": [
    "If any of the following terms are found in an advertisement, reject the ad only. Do not issue a phone blacklist.",
    "Crowbar",
    "All fabric",
    "Head bag (except luminous head bag)",
    "Animal skin",
    "Armor skin",
    "Air Horn",
    "Earplugs",
    "Barricade",
    "Trap",
    "Poison dart",
    "Army Uniform",
    "Tracking sensor",
    "Dangerous razor",
    "Resource scanners",
    "Body armor plates",
    "Body Armor",
    "Ingredients for cocaine",
    "Paper for money",
    "Satellite dish",
    "Tincture of forest mushrooms",
    "First Aid Kits & all pills",
    "Food items (Banana, Burger, Grilled Steak)"
  ],
  "cannotAdvertise": [
    "Things We Cannot Advertise",
    "Advertisements involving any of the following must be rejected:",
    "Grand Coins (Premium Battlepass / Premium Plus Battlepass)",
    "All illegal items listed above",
    "Lockpicks, ropes, and crowbars",
    "Specific family names",
    "“Looking for Playboy family members.” advertisements",
    "(Family names cannot be mentioned)",
    "Hype Body or branded armor",
    "Gangs",
    "Nationality",
    "Anything involving the sale of people",
    "Anything sexual or hinting at sexual content",
    "Drugs of any kind",
    "Food items (except fish)",
    "Health products (medkits, pills, tincture soup, etc.)",
    "Birthday advertisements",
    "Leaders and deputy leaders  (excluding leaders of unofficial organization families and crime organizations)"
  ],
  "placesNotPromote": [
    "Punishment: Warning",
    "The following locations, organizations, or events are not allowed to be promoted in advertisements:",
    "Mega Mall",
    "Gang Headquarters (Ballas, Vagos, Families, Bloods, and Marabunta)",
    "Black Market",
    "Parties at LSPD, FIB, SAHP, EMS, LifeInvader or Government buildings.",
    "Parties at the ghetto",
    "Please make sure all advertisements follow these guidelines before publishing."
  ],
  "officialPlaces": [
    "Vinewood Hills",
    "Rockford Hills",
    "Richman",
    "Sandy Shores",
    "Paleto Bay",
    "Postal",
    "Hospital",
    "Capitol",
    "Fire Station",
    "Auto Fair",
    "Bahama Mamas Bar",
    "Tequi-la-la Bar",
    "FIB",
    "Hotel Spa Bar",
    "Pacific Bluffs Country Club",
    "Diamond Resort Bar (Casino Restaurant)",
    "Vanilla Unicorn Bar",
    "Church",
    "Stock Exchange",
    "Stadium",
    "Chumash",
    "Lifeinvader",
    "Del Perro Pier",
    "Del Perro Beach",
    "Cayo Perico Island",
    "Hotel",
    "Raton Canyon",
    "School",
    "SAHP",
    "Mirror Park"
  ],
  "unofficialPlaces": [
    "airport",
    "autosalon",
    "beach",
    "beach market",
    "ghetto",
    "post office",
    "train station",
    "yacht"
  ],
  "terms": {
    "looking to buy": "Buying",
    "looking to purchase": "Buying",
    "max config": "with full configuration",
    "max tuning": "with full configuration",
    "fully upgraded": "with full configuration",
    "nearly max": "with partial configuration",
    "(part)lvl3 or below": "with partial configuration",
    "body upgrades": "with visual upgrades",
    "body kit": "with visual upgrades",
    "turbo": "turbo kit",
    "drift tuning": "drift kit",
    "drift assistance": "drift kit",
    "luminous rims": "luminous wheels",
    "unique wheels": "luminous wheels",
    "level 1": "low quality",
    "low level": "low quality",
    "level 2": "medium quality",
    "medium level": "medium quality",
    "level 3": "high quality",
    "high level": "high quality",
    "level 4": "max quality",
    "max level": "max quality",
    "crates": "containers",
    "cases": "containers",
    "spray cans": "paint cans",
    "spray balloons": "paint cans",
    "extras": "of type",
    "personal business": "private business",
    "drug lab": "Burger shop"
  }
};
