(()=>{
const P=window.LIFEINVADER_POLICY||{};
const n=s=>String(s||'').replace(/[“”]/g,'"').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
const l=s=>n(s).toLowerCase();
const esc=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function hasTerm(t,p){const x=l(t),q=l(p);if(q==='firearms of any kind')return /\bfirearms?\b/i.test(x);if(q==='drugs and cocaine'||q==='drugs of any kind')return /\bdrugs?\b|\bcocaine\b/i.test(x);if(q==='weed / cannabis seeds or trees')return /\bweed\b|\bcannabis\b/i.test(x);if(q==='anything sexual or hinting at sexual content')return /\bsexual\b|\bsex\b/i.test(x);if(q==='anything involving the sale of people')return /\bsell(?:ing)?\s+(?:a\s+)?people\b/i.test(x);if(q==='hype body or branded armor')return /\bhype body\b|\bbranded armor\b/i.test(x);if(q==='nationality')return /\bnationalit(?:y|ies)\b/i.test(x);if(q==='gangs')return /\bgangs?\b/i.test(x);if(q==='food items (except fish)')return /\bbanana\b|\bburger\b|\bgrilled steak\b/i.test(x);if(q==='health products (medkits, pills, tincture soup, etc.)')return /\bmedkits?\b|\bpills?\b|\btincture soup\b/i.test(x);return x.includes(q)}
const action=t=>{const x=l(t);if(/^party\b/.test(x))return'party';if(/^selling or trading\b/.test(x))return'selling or trading';if(/^renting out\b/.test(x))return'renting out';if(/^renting\b/.test(x))return'renting';if(/^trading\b/.test(x))return'trading';if(/^buying\b/.test(x))return'buying';if(/^selling\b/.test(x))return'selling';if(/^hiring\b/.test(x))return'hiring';if(/^looking for\b/.test(x))return'looking for';return''};
const category=t=>{const x=l(t);if(/^party\b/.test(x))return'Other';if(/\b(adder|albany escalade|alpha|annis 350z|annis gt-r i|annis rx-7|annis rx-8|annis silvia|annis skyline|annis wrx|annis zr-350|apocalypse impaler|apocalypse imperator|apocalypse issi|apocalypse slamvan)\b/i.test(x))return'Auto';if(/\b(house|apartment|mansion|casino penthouse|property|g\.s\.|w\.h\.)\b/.test(x))return'Real Estate';if(/\b(car|cars|vehicle|motorcycle|motorcycles|bike|bikes|atv|boat|boats|helicopter|helicopters|plane|planes|turbo kit|drift kit)\b/.test(x))return'Auto';if(/\b(business|store|gas station|taxi company|hair salon|jewelry store|service station|car sharing|private business)\b/.test(x))return'Business';if(/\b(hiring|job|work|salary|years experience)\b/.test(x))return'Work';if(/\b(boyfriend|girlfriend|husband|wife|valentine|dating|looking for)\b/.test(x))return'Dating';if(/\b(discount|%\s*off|\boff\b)/.test(x))return'Discounts';if(/\b(service|template|party|wedding|dj|singer|lawyer|personal driver|professional dancer)\b/.test(x))return'Services';return'Other'};
function corrections(t){let o=t,c=[];Object.entries(P.terms||{}).sort((a,b)=>b[0].length-a[0].length).forEach(([a,b])=>{const r=new RegExp(esc(a),'gi');if(r.test(o)){o=o.replace(r,b);c.push(`Changed “${a}” to “${b}”.`)}});return{o,c}}
function check(text){const raw=n(text);const r={input:raw,output:raw,category:category(raw),severity:'PASS',issues:[],corrections:[],manual:[]};if(!raw){r.severity='WARNING';r.issues.push({type:'WARNING',text:'Enter an advertisement to run the policy checker.'});return r}
for(const t of P.blacklist||[])if(hasTerm(raw,t))r.issues.push({type:'BLACKLIST',text:`Blacklist term detected: ${t}`});
for(const t of [...(P.rejectOnly||[]),...(P.cannotAdvertise||[])])if(hasTerm(raw,t))r.issues.push({type:'REJECT',text:`Policy restriction detected: ${t}`});for(const t of (P.placesNotPromote||[]))if(hasTerm(raw,t))r.issues.push({type:'WARNING',text:`Location/event is not promoted: ${t}`});
const a=action(raw);
if(/\bparty\s+at\s+(?:the\s+)?ghetto\b/i.test(raw)||/\bblack market\b/i.test(raw)||/\bmega mall\b/i.test(raw)||/\b(gang headquarters|ballas|vagos|families|bloods|marabunta)\b/i.test(raw))r.issues.push({type:'WARNING',text:'This location/organization is listed under Places We Do Not Promote.'});
if(/\bparty\s+at\s+the\s+beach\s+market\b/i.test(raw)){r.issues.push({type:'CORRECTION',text:'Use “Party at the Beach.” instead of “Party at the Beach Market.”'});}
if(/\b(green zone|green grass)\b/i.test(raw))r.issues.push({type:'WARNING',text:'Green grass/green zone wording is not promoted.'});
if(!a)r.issues.push({type:'REJECT',text:'Advertisement must begin with an approved action.'});
if(a==='buying'&&!/\bbudget\s*:/i.test(raw)){r.issues.push({type:'CORRECTION',text:'Buying ads require Budget:. Use Negotiable when no budget is provided.'})}
if(['selling','trading','selling or trading'].includes(a)&&!/\bprice\s*:/i.test(raw))r.issues.push({type:'CORRECTION',text:'Selling/trading ads require Price:. Use Negotiable when no price is provided.'});
if(a==='renting out'&&!/\brent\s*:/i.test(raw))r.issues.push({type:'CORRECTION',text:'Renting out ads use Rent: instead of Price:.'});
if(/,\d{3}(?:\D|$)/.test(raw)&&/\$\s*[\d,.]+/.test(raw))r.issues.push({type:'CORRECTION',text:'Use a full stop (.) instead of a comma (,) for prices.'});
if(/\$\s*\d+(?:\.\d+)?[km]\b/i.test(raw))r.issues.push({type:'CORRECTION',text:'Do not use k or M; write the number in the policy format.'});
if(/(?:price|budget|rent)\s*:\s*\d/i.test(raw)&&!/\$\s*\d/i.test(raw))r.issues.push({type:'CORRECTION',text:'A dollar sign ($) must be used before monetary values.'});
if(/[A-Za-z)]$/.test(raw))r.issues.push({type:'CORRECTION',text:'Add a full stop (.) when the ad ends with a letter.'});
for(const p of P.officialPlaces||[]){const re=new RegExp(`\\b${esc(p)}\\b`,'i');const m=raw.match(re);if(m&&m[0]!==p)r.issues.push({type:'CORRECTION',text:`Use official capitalization: ${p}.`})}
for(const p of P.unofficialPlaces||[]){const re=new RegExp(`\\b(?:the\\s+)?${esc(p)}\\b`,'i');const m=raw.match(re);if(m&&!/^the\s+/i.test(m[0])&&p!=='post office')r.issues.push({type:'CORRECTION',text:`Use “the ${p}” for unofficial locations.`})}
if(r.category==='Auto'){const vh=['Adder','Albany Escalade','Alpha','Annis 350Z','Annis GT-R I','Annis RX-7','Annis RX-8','Annis Silvia','Annis Skyline','Annis WRX','Annis ZR-350','Apocalypse Impaler','Apocalypse Imperator','Apocalypse Issi','Apocalypse Slamvan'];const hits=vh.filter(v=>hasTerm(raw,v));if(hits.length>1&&!/^trading\b/i.test(raw))r.issues.push({type:'REJECT',text:'Cannot advertise more than 1 vehicle at a time unless they are trading.'});if(hits.length===1&&!/"[^\"]+"/.test(raw)&&!/^buying a car\b/i.test(raw))r.issues.push({type:'CORRECTION',text:'Specific vehicle brand/model should be in quotes from the vehicle list.'});if(/\b(insurance)\s+\d+\s+days?\b/i.test(raw))r.issues.push({type:'CORRECTION',text:'Do not mention insurance days; use “with insurance”.'});if(/\b(luminous rims|unique wheels)\b/i.test(raw))r.issues.push({type:'CORRECTION',text:'Use “luminous wheels” instead.'})}
if(r.category==='Real Estate'){if(/\b(trading|selling or trading)\b/i.test(raw))r.issues.push({type:'REJECT',text:'Houses and apartments are not tradable.'});const nums=(raw.match(/№\s*\d+/g)||[]).length;if(nums>1)r.issues.push({type:'REJECT',text:'Only one numbered property is allowed per ad.'})}
if(r.category==='Business'){const biz=['ammunition store','atm business','bar','car wash','car sharing','chip tuning','clothing shop','electric station','farm','flower shop','fight club','furniture shop','gas station','grand elite','hair salon','jewelry store','juice shop','luna park','parking','pet shop','state object','service station','tattoo studio','taxi company','warehouse','24/7 store','burger shop','cowshed','freight train','plantation','oil well'];const hits=biz.filter(v=>hasTerm(raw,v));if(hits.length>1)r.issues.push({type:'REJECT',text:'Only one business should be promoted in an ad.'});if(/\bfamily business\b/i.test(raw)&&/\btrading\b/i.test(raw))r.issues.push({type:'REJECT',text:'Family businesses cannot be traded.'});const ms=[...raw.matchAll(/\$\s*([\d.]+)\s*Million/gi)];if(ms.some(m=>parseFloat(m[1].replace(/\./g,''))>500))r.issues.push({type:'CORRECTION',text:'Business prices above $500 Million must be changed to Negotiable.'})}
if(r.category==='Dating'&&/^looking for\b/i.test(raw)){const t=raw.replace(/^looking for\s+/i,'').split(/[.!?]/)[0].trim();if(t.split(/\s+/).length<2&&!/\b(family|boyfriend|girlfriend|husband|wife|friend|friends|date|valentine)\b/i.test(t))r.issues.push({type:'REJECT',text:'Please mention the Full Name for a specific person.'});else r.manual.push('For a specific person, search the full name in the Grand RP mail/database before approval.')}
if(r.category==='Services')r.manual.push('Verify the exact approved LifeInvader template exists before publishing.');
if((a==='renting out'||a==='renting')&&!/\b(?:\d+\s*days?|per week|for \d+\s*days?)\b/i.test(raw))r.issues.push({type:'REJECT',text:'Please indicate the rental period.'});
if(/\b(play dice|play poker)\b/i.test(raw)){if(!/\bbet\s*:/i.test(raw))r.issues.push({type:'CORRECTION',text:'Use “Bet: Negotiable.” when no bet is specified.'});const m=raw.match(/\bbet\s*:\s*\$\s*([\d.]+)\s*Million/i);if(m&&parseFloat(m[1].replace(/\./g,''))>10)r.issues.push({type:'CORRECTION',text:'Bets above $10 Million must be changed to Negotiable.'})}
if(/\bbeach market\b/i.test(raw)){if(/\bcheap prices?\b/i.test(raw))r.issues.push({type:'CORRECTION',text:'Change “cheap prices” to “for good prices”.'});const known=['panda','duckling','fancy bear','kitty bunny','hippo','robot','cyberdog','robobeast','grand ticket','seed','juice','battery','luminous','pineapple','mandarin','cabbage','pumpkin'];const hits=known.filter(v=>hasTerm(raw,v));if(hits.length>1)r.issues.push({type:'CORRECTION',text:'Beach Market ads may mention only one item name; use “various items” for multiple items.'})}
const c=corrections(raw);r.output=c.o;r.corrections=c.c;
// Enforce the policy's required capitalization for the leading action.
const actionFix={buying:'Buying',selling:'Selling',trading:'Trading','selling or trading':'Selling or trading','renting out':'Renting out',renting:'Renting',hiring:'Hiring'};
if(a && actionFix[a]){const lead=new RegExp('^'+esc(a),'i');if(lead.test(r.output)){const next=r.output.replace(lead,actionFix[a]);if(next!==r.output){r.output=next;r.corrections.push(`Capitalized the leading action to “${actionFix[a]}”.`)}}}
// Progen is a proper name in the uploaded examples; normalize it when used as a standalone token.
if(/\bprogen\b/i.test(r.output)){const next=r.output.replace(/\bprogen\b/gi,'Progen');if(next!==r.output){r.output=next;r.corrections.push('Capitalized “Progen” as a proper name.')}}

if(a==='buying'&&!/\bbudget\s*:/i.test(r.output)){r.output=r.output.replace(/[.]?\s*$/,'')+'. Budget: Negotiable.';r.corrections.push('Added “Budget: Negotiable.” because the buying ad had no budget.')} 
if(['selling','trading','selling or trading'].includes(a)&&! /\bprice\s*:/i.test(r.output)){r.output=r.output.replace(/[.]?\s*$/,'')+'. Price: Negotiable.';r.corrections.push('Added “Price: Negotiable.” because the ad had no price.')} 
if(a==='party' && !/[.]$/.test(r.output)) {r.output=r.output+'.';r.corrections.push('Added a full stop to the party advertisement.')}if(r.issues.some(i=>i.type==='BLACKLIST'))r.severity='BLACKLIST';else if(r.issues.some(i=>i.type==='REJECT'))r.severity='REJECT';else if(r.issues.length||r.manual.length)r.severity='CHECK';return r}
window.LifeInvaderPolicy={check};
})();